### ISSUE TITLE
Identify default mod skins from sources like RSS

### ISSUE THREAD

**Issue by okletzmayr** [gro-ove/actools-data#2]
Since CM is already displaying origin icons for cars by bigger modding teams like RSS and AD, I think it would be a nice feature to mark the default skins with their icon as well.

Just an idea I got while setting up a server with the new RSS Formula Hybrid 2018, and seeing that CM wanted me to supply download URLs for the default skins:
![rss_skins_marked_as_missing](https://user-images.githubusercontent.com/5478672/38093336-e8e96126-336a-11e8-86c9-056875fcbcc0.PNG)

I own every RSS mod except Formula '79, so I quickly compiled a JSON of every default skin [in my fork](https://github.com/okletzmayr/actools-data/blob/modskins/Miscellaneous/ModSkins.json).
Let me know if this is of any use or whether you want to support this at all.

**Comment by okletzmayr** [comment]
just FYI, I added both the RSS Formula 79 default skins and the DRM Revival default skins to my fork (now in a [separate branch](https://github.com/okletzmayr/actools-data/blob/modskins/Miscellaneous/ModSkins.json)). I'll also try to write the CM code to use this data, but that might take some time since I'm not really used to working with C#.

**Comment by gro-ove** [comment]
Thank you, I’ll add that! And maybe add extra fields into ui_skin.json, like author. The problem is that with them, stock launcher shows an error, but at least it works now with them, so there it’s not that big of an issue.
